// SUBREDDIT - ACTION TYPES
// =============================================================================

export const SUBREDDIT_QUERY_REQUEST = "SUBREDDIT_QUERY_REQUEST";
export const SUBREDDIT_QUERY_SUCCESS = "SUBREDDIT_QUERY_SUCCESS";
export const SUBREDDIT_QUERY_FAILURE = "SUBREDDIT_QUERY_FAILURE";

export const SUBREDDIT_TARGET_UPDATE = "SUBREDDIT_TARGET_UPDATE";
export const SUBREDDIT_SELECTED_UPDATE = "SUBREDDIT_SELECTED_UPDATE";
